### ISSUE TITLE
Using client-js inside Vue3 application

### ISSUE THREAD

**Issue by re2005** [Web3-API/prototype#1161] opened 2022-08-19 08:55 UTC
I'm following the guide https://docs.polywrap.io/reference/clients/js/client-js

```ts
import { PolywrapClient } from '@polywrap/client-js';

const polywrap = new PolywrapClient();
const manifest = await polywrap.getManifest('wrap://ipfs/QmWTC8Y4R8WoHSoAeKaLyJtHyH3jucXmArqrps5XZwXzLn', {});
console.log(manigest)
```

Running the same just inside a node script works fine, but when running in  my Vue3 app it is getting an error:

![image](https://user-images.githubusercontent.com/2920357/185582971-60470026-5ce7-4a25-b2a3-531dc631c3b3.png)
![image](https://user-images.githubusercontent.com/2920357/185583049-4a3fafc1-c68c-414c-abcd-ab149a9a2929.png)

Any idea or help is very welcome.

Thanks!

**Comment by re2005** [comment] 2022-08-19 09:00
It may has something todo with `Vite`

When upgraded to `Vite3`  now I see this error:

```
Module "url" has been externalized for browser compatibility. Cannot access "url.parse" in client code.
at node_modules/@apidevtools/json-schema-ref-parser/lib/util/url.js (url.js:25:17)
```

**Comment by cbrzn** [comment] 2022-08-19 10:15
Hey @re2005 thanks for opening the issue. I think this might be related to https://github.com/polywrap/monorepo/issues/985 - Would it be possible for you to remove any minification from your build just to check that indeed this is the problem?

We are currently trying to solve this issue. In advance, sorry for this.

Regarding:

> It may has something todo with `Vite`
> 
> When upgraded to `Vite3` now I see this error:
> 
> ```
> Module "url" has been externalized for browser compatibility. Cannot access "url.parse" in client code.
> at node_modules/@apidevtools/json-schema-ref-parser/lib/util/url.js (url.js:25:17)
> ```

My first thought is that you will need to add a polyfill for `url`

**Comment by re2005** [comment] 2022-08-19 12:25
@cbrzn Thanks for quick reply.

I've disabled `minification` and still same issue. Have also tried to `polyfill` the `url` but no success.

Will keep on trying.
Cheers.

**Comment by cbrzn** [comment] 2022-08-19 12:29
@re2005 interesting, can you please share a repository to reproduce this and help you?

**Comment by re2005** [comment] 2022-08-19 13:41
I've a reproduction repository right here:

https://github.com/re2005/polywrap-test

**Comment by cbrzn** [comment] 2022-08-23 12:41
Hey since you were able to run the client with the fix I will go ahead and close this issue @re2005 feel free to reopen if I am missing something

**Closed as completed by cbrzn** 2022-08-23 12:41 UTC
