### ISSUE TITLE
Workflows Should Use Polywrap Manifest Best-Practices

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1044] opened 2022-07-13 07:51 UTC
Currently the workflow file is being "blindly" parsed & loaded:
https://github.com/polywrap/monorepo/blob/4eac9010f4b3cb7cd041854a737bd84e176d816c/packages/cli/src/commands/run.ts#L79-L81

We should follow the best-practices we have put in place for the other Polywrap manifests, by first defining a JSON-Schema here: https://github.com/polywrap/monorepo/tree/origin/packages/manifests/polywrap/formats

This will allow us to use the generated type in `core`, and automatically validate the input file by using the `deserializeWorkflowManifest` function that's exported from here for each manifest type: https://github.com/polywrap/monorepo/tree/origin/packages/js/manifests/polywrap/src/formats

**Comment by dOrgJelli** [comment] 2022-09-07 03:57
Hey @Niraj-Kamdar, can this be completed?

**Comment by fetsorn** [comment] 2022-09-07 07:57
I think this is completed as duplicate of #970 and #1131

**Closed as completed** 2022-09-08 07:48 UTC
